### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by melisatallis** [geminiplanetimager/gpipsfs#4]
Need to install gpi pipeline in machine to use pysenphot

**Comment by melisatallis** [comment]
GPI_tweeter_actuators.fits not in gpipsfs/data/

**Comment by melisatallis** [comment]
Need to install poppy 0.7.0

**Comment by mperrin** [comment]
I agree about these: 

> Need to install gpi pipeline in machine to use pysenphot
> Need to install poppy 0.7.0

As for this one:
> GPI_tweeter_actuators.fits not in gpipsfs/data/

That file _is_ included in that directory; for instance you can see it listed at https://github.com/geminiplanetimager/gpipsfs/tree/master/gpipsfs/data 

I think the issue must be that when you installed the package, that data didn't get copied from the repo directory into the python `site-packages` directory.  The quick fix / workaround is for you to install the package in developer mode: ``python setup.py develop`` instead of ``python setup.py install``. Without going into the details of how that works behind the scenes, I believe that should get things working for you quickly. And I'll go ahead and clean up the install docs and procedures on my end. 

Thanks for this feedback!

**Comment by mperrin** [comment]
aha yes, it was set up to install the "\*.txt" data files but also needs to grab "\*.fits"

**Comment by mperrin** [comment]
Should be all fixed now - @melisatallis you could check out the updated README file and see if that looks good? And if you update your copy of the repo, you should now be able to do ``python setup.py install`` and have it move the tweeter data file.
